app/__init__.py
from flask import Flask
from flask_sqlalchemy import SQLAlchemy
from flask_migrate import Migrate
from flask_bcrypt import Bcrypt

db = SQLAlchemy()
migrate = Migrate()
bcrypt = Bcrypt()

def create_app(config_forum):
    app = Flask(__name__)
    app.config.from_object(config_forum)

    bcrypt.init_app(app)
    db.init_app(app)


    with app.app_context():
        migrate.init_app(app, db)


    from .main import main
    from .auth import auth
    from .question import question

    app.register_blueprint(main, url_prefix='/')
    app.register_blueprint(auth, url_prefix='/auth')
    app.register_blueprint(question, url_prefix='/question')

    app.jinja_env.globals.update(zip=zip)
    app.jinja_env.globals.update(len=len)

    return app

app/main/__init__.py
from flask import Blueprint

main = Blueprint('main', __name__)


from . import views

app/main/views.py
from flask import Flask, redirect, render_template, request, session

from . import main

@main.route('/', methods=['POST', 'GET'])
def index():
    if request.method == 'POST':
        pass
    if 'username' in session:
        return render_template('index.html', username=session['username'])
    else:
        return render_template('index.html', username='guest')

app/question/__init__.py
from flask import Blueprint

question = Blueprint('question', __name__, template_folder='templates')


from . import views

app/question/views.py
from flask import Flask, redirect, render_template, request, session, url_for

from . import question
from app.model import Question, Comment
from app.model_manage import add_question, get_question, update_question
from app.model_manage import add_comment, delete_comment as del_comment


@question.route('/')
def index():
    questions = Question.query.all()
    return render_template('questions.html', questions=questions)


@question.route('/<page_id>', methods=['GET', 'POST'])
def page(page_id):
    if request.method == 'POST':
        if request.form['submit'] == 'Add comment':
            add_comment(content=request.form['content'], question=get_question(id=page_id))
    question = get_question(id=page_id)
    if not 'username' in session:
        return render_template('question_page.html', question=question) 
    if session['username'] == question.user.username:
        return render_template('question_page.html', question=question, question_edit=True, current_username=session['username'])
    return render_template('question_page.html', question=question, current_username=session['username'])
    

@question.route('/<page_id>/<comment_id>')    
def delete_comment(page_id, comment_id):
    del_comment(id=comment_id)
    return redirect(url_for('question.page', page_id=page_id))


@question.route('/add_question', methods=['GET', 'POST'])
def add():
    if not 'username' in session:
        return redirect(url_for('auth.login'))
    if request.method == 'POST':
        if get_question(title=request.form['title']):
            return render_template('edit_question.html', error='This question already exist')
        add_question(title=request.form['title'], content=request.form['description'])
        return redirect(url_for('question.index'))
    else:
        return render_template('edit_question.html')
    
@question.route('/edit_question/<page_id>', methods=['GET', 'POST'])
def edit(page_id):
    if request.method == 'POST':
        question = get_question(title=request.form['title'])
        if question:
            if question.id != page_id:
                return render_template('edit_question.html', error='This question already exist')
        question = get_question(id=page_id)
        update_question(question=question, title=request.form['title'],\
                         content=request.form['content'])
        return redirect(url_for('question.page'), page_id=page_id)
    else:
        return render_template('edit_question.html')
    

app/question/templates/add_question.html
{% extends "base.html" %}

{% block title %}Add question{% endblock %}

{% block content %}
{% if error %}
    <font color="red"><center>{{ error }}!</center></font>
{% endif %}
    <form action="" method="post">
        <fieldset style="width:20px">
            <legend>Add question</legend>
            <p>
                <label for="title">Title:</label>
                <input type="text" name="title" id="title" required>
            </p>
            <p>
                <label for="description">Description:</label>
                <textarea name="description" id="description"></textarea>
            </p>
            <p><input type="submit" value="Submit"></p>
        </fieldset>
    </form>
{% endblock %}

app/question/templates/edit_question.html
{% extends "base.html" %}

{% block title %}Add question{% endblock %}

{% block main %}
{% if error %}
    <font color="red"><center>{{ error }}!</center></font>
{% endif %}
    <form action="" method="post">
        <fieldset style="width:20px">
            <legend>Add question</legend>
            <p>
                <label for="title">Title:</label>
                <input type="text" name="title" id="title" required>
            </p>
            <p>
                <label for="description">Description:</label>
                <textarea name="description" id="description"></textarea>
            </p>
            <p><input type="submit" value="Submit"></p>
        </fieldset>
    </form>
{% endblock %}

app/question/templates/question_page.html
{% extends "base.html" %}

{% block title %}Question {{ question.id }}{% endblock %}

{% block head %}
<link href="{{ url_for('static', filename='css/question_page.css') }}" rel="stylesheet">
{% endblock %}


{% block main %}

<section>

    <div class="question">

        <div class="title">
            <h1>{{ question.title }}</h1>
            {% if question_edit %}
            <a href="{{ url_for('question.edit', page_id=question.id) }}"><ion-icon name="create-outline"></ion-icon></a>
            {% endif %}
        </div>
        
        <div class="content">
            <p>{{ question.content }}</p>
        </div>

        <p class="time">Published: {{ question.date.strftime("%d-%m-%Y %H:%M:%S") }}</p>
    </div>

    <div class="comments">

        <form action="" method="post" class="add-comment">
            <textarea name="content"></textarea>
            <input type="submit" name="submit" value="Add comment">
        </form>


        {% for comment in question.comments %}
        <div class="comment">
            <div class="comment-head">
                <div class="wrap">
                    {% if comment.user.username ==  current_username %}
                    <a href="{{ url_for('question.delete_comment', page_id=question.id, comment_id=comment.id) }}"><ion-icon name="close-circle-outline"></ion-icon></ion-icon></a>
                    {% endif %}
                    <p class="time">{{ comment.date.strftime("%d-%m-%Y %H:%M:%S") }}</p>
                </div>
                <p class="author">{{ comment.user.username }}</p>
            </div>
            <p class="content">{{ comment.content }}</p>
        </div>
        {% endfor %}
        

    </div>

</section>

{% endblock %}  

app/question/templates/questions.html
{% extends "base.html" %}

{% block title %}Questions{% endblock %}

{% block head %}
<link href="{{ url_for('static', filename='css/questions.css') }}" rel="stylesheet">
{% endblock %}


{% block main %}

<section>
    <a href="{{ url_for('question.add') }}" class="add-button">Add question</a>
    <h1>Questions:</h1>
    <l class="questions">
        {% for i, question in zip(range(1, len(questions) + 1), questions) %}
        <li onclick="location.href='{{ url_for('question.page', page_id=question.id) }}';">
            <h2>{{ i }}. {{ question.title }}</h2>
            <p>{{ question.date.strftime("%d-%m-%Y %H:%M:%S") }}</p>
        </li>
        {% endfor %}
    </ul> 
</section>



{% endblock %}

app/templates/base.html
<head>
    <link href="{{ url_for('static', filename='css/base.css') }}" rel="stylesheet">
    <title>{% block title %}{% endblock %}</title>
    {% block head %}
    {% endblock %}
</head>
<body>
    <div class="header">
        <div class="hat">
            <h1>Ответ на сотку!</h1>
        </div>
        <div class="nav">
            <ul>
                <li><a href="{{ url_for('main.index') }}">Home</a></li>
                <li><a href="{{ url_for('auth.login') }}">Sign in</a></li>
                <li><a href="{{ url_for('auth.logout') }}">Logout</a></li>
                <li><a href="{{ url_for('auth.delete') }}">Delete user</a></li>
            </ul>
        </div>
    </div>

    <div class="main">
        {% block main %}
        {% endblock %}
        <script type="module" src="https://unpkg.com/ionicons@5.5.2/dist/ionicons/ionicons.esm.js"></script>
        <script nomodule src="https://unpkg.com/ionicons@5.5.2/dist/ionicons/ionicons.js"></script>
    </div>


    <div class="footer">
        <p class="bg-href">Изображение от <a href="https://ru.freepik.com/free-vector/gradient-white-monochrome-background_15782163.htm#query=white%20background%20full%20hd&position=48&from_view=search&track=robertav1">Freepik</a></p>
        <p class="contacts">Contacts: InfaNaSotku@gmail.com</p>
    </div>


</body>

app/templates/index.html
{% extends "base.html" %}

{% block title %}Index{% endblock %}

{% block head %}
<link href="{{ url_for('static', filename='css/index.css') }}" rel="stylesheet">
{% endblock %}

{% block main %}
<section>
    <h2>Hi, {{ username }}!</h2>
    <div class="wrap"  onclick="location.href='{{ url_for('question.index') }}';">
        <p>Questions</p>
        <div class="ring">
            <span></span>
            <span></span>
            <span></span>
        </div>
    </div>
 </section>
{% endblock %}

app/templates/login.html
{% extends "base.html" %}

{% block title %}Login{% endblock %}

{% block head %}
<link href="{{ url_for('static', filename='css/login.css') }}" rel="stylesheet">
{% endblock %}

{% block main %}
<section>
    <div class="form-box">
        <form action="" method="post">
            <h2>Sign in</h2>
            <div class="inputbox">
                <ion-icon name="person-outline"></ion-icon>
                <input type="text" name="username" id="username" required>
                <label for="username">Username:</label>
            </div>
            <div class="inputbox">
                <ion-icon name="lock-closed-outline"></ion-icon>
                <input type="password" name="password" id="password" required>
                <label for="password">Password:</label>
            </div>
            {% if error %}
            <font color="red"><center>{{ error }}!</center></font>
            {% endif %}
            <input type="submit" value="Sign in">
            <div class="register-redirect">
                <p>Don't have an account <a href="{{ url_for('auth.register') }}">Register</a></p>
            </div>
        </form>
    </div>
</section>
{% endblock %}

app/templates/register.html
{% extends "base.html" %}

{% block title %}Register{% endblock %}

{% block head %}
<link href="{{ url_for('static', filename='css/login.css') }}" rel="stylesheet">
{% endblock %}

{% block main %}
<section>
    <div class="form-box" style="height: 400px; transform: translateY(-30%);">
        <form action="" method="post">
            <h2>Sign in</h2>
            <div class="inputbox">
                <ion-icon name="person-outline"></ion-icon>
                <input type="text" name="username" id="username" required>
                <label for="username">Username:</label>
            </div>
            <div class="inputbox">
                <ion-icon name="lock-closed-outline"></ion-icon>
                <input type="password" name="password" id="password" required>
                <label for="password">Password:</label>
            </div>
            <div class="inputbox">
                <ion-icon name="checkmark-circle-outline"></ion-icon>
                <input type="password" name="confirm password" id="confirm password" required>
                <label for="confirm password">Confirm password:</label>
            </div>
            {% if error %}
            <font color="red"><center>{{ error }}!</center></font>
            {% endif %}
            <input type="submit" value="Sign up">
        </form>
    </div>
</section>
{% endblock %}

templates/base.html
<head>
    <title>{% block title %}{% endblock %} - page</title>
    {% block head %}
    {% endblock %}
</head>
<body>
    <p>
        <a href="{{ url_for('index') }}">Home</a>
        <a href="{{ url_for('login') }}">Login</a>
        <a href="{{ url_for('logout') }}">Logout</a>
    </p>
    {% block content %}
    {% endblock content %}
</body>